name: Deploy application to AKS

on:
 push:
   branches:
   - main

jobs:
 deploy: 
   runs-on: ubuntu-latest

steps:
- name: checkout code
  uses: actions/checkout@v2

- name: Login to Azure CLI 
  uses: azure/login@v1
  with:
    username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
    password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    
- name: Pull the Images from Azure ACR
  run: |
    az acr login --name webappacr01
    docker pull webappacr01.azurecr.io/mywebappacr:latest
    docker tag  webappacr01.azurecr.io/mywebappacr:latest webappacr01.azurecr.io/mywebappacr:lts

- name: Configure Kubectl
  uses: azure/setup-kubectl@v1.0.1
  with:
    secrets: ${{ secretes.KUBECONFIG }}

- name: Deploy application to AKS
  run: |
    kubectl apply -f /home/adm-deepika/azuredemoproject/Deployment.yaml

- name: Update kubernetes service 
  run: | 
    kubectl apply -f /home/adm-deepika/azuredemoproject/service.yaml
    
