name: Build Container Image and Push it to ACR

on:
 workflow_dispatch:
  
jobs:
  build-and-push:
   runs-on: ubuntu-latest
   
   steps:
   - name: Login to Azure Registry 
     uses: docker/login-action@v1
     with:
       username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
       password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
       registry: webappacr01.azurecr.io
  
   - name: Pull the Images from Azure ACR
     run: |
       az acr login --name webappacr01
       
   - name: setup Kubectl
     uses: azure/setup-kubectl@v3

   - name: Configure Kubernetes CLI
     run: kubectl config set-context your-deploy-aks --cluster=webappaks --user=clusterUser_webappaks

   - name: checkout code
     uses: actions/checkout@v2
        
   - name: Deploy application to AKS
     run: |
       kubectl apply -f Deployment.yaml

   - name: Deploy application to AKS
     run: |
       kubectl apply -f service.yaml

   


     
