name: Pull Image from ACR & Deploy to AKS

on:
 workflow_dispatch:
  
jobs:
  build-and-push:
   runs-on: ubuntu-latest
   
   steps:
   - name: Login to Azure Registry 
     uses: docker/login-action@v1
     with:
       username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
       password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
       registry: webappacr01.azurecr.io

   - name: Configure Azure CLI 
     run: az configure --defaults acr=webappacr01
     
  # - name: Pull the Images from Azure ACR
   #  run: az aks update --name webappaks --resource-group adm-deejayac1 --attach-acr webappacr01
     #uses: azure/acr-task-action@v1
     #with:
       #image: webappacr01.azurecr.io/mywebappacr:latest
       
   - name: setup Kubectl
     run: 	az aks get-credentials --resource-group adm-deejayac1 --name myAKSDemo


     # name: Configure Kubernetes CLI
     #run: kubectl config set-context your-deploy-aks --cluster=webappaks --user=clusterUser_webappaks

   - name: checkout code
     uses: actions/checkout@v2
        
   - name: Deploy application to AKS
     run: |
       kubectl apply -f /home/adm-deepika/azuredemoproject/deployment.yaml

   - name: Deploy application to AKS
     run: |
       kubectl apply -f /home/adm-deepika/azuredemoproject/service.yaml

   


     
