name: Build Container Image and Push it to ACR 

on:
 workflow_dispatch:
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - uses: action/checkout@v2
   - uses: azure/docker-login@v1
     with:
      login-server: webappacr.azurecr.io
      username: ${{ secrets.ACR_USERNAME }}
      password: ${{ secrets.ACR_PASSWORD }}
   - run: |
      docker build -t webappacr.azurecr.io/mywebapp:v1 .
      docker push webappacr.azurecr.io/mywebapp:v1 .

 
