name: Build Container Image and Push it to ACR

on:
 push:
  branches:
    - main
  
jobs:
  build-and-push:
   runs-on: ubuntu-latest
   
   steps:
   - name: Login to Docker Registry 
     uses: docker/login-action@v3
     with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
  
   - name: Pull the Images from Dockerhub
     run: docker pull deepikajag/aks-webapp:lts
    
   - name: Configure Kubectl
     uses: azure/setup-kubectl@v3

   - name: setup kubelogin
     uses: azure/use-kubelogin@v1
     with:
       kubelogin-version: 'v0.0.24'

   - name: set AKS content
     id: set-context
     uses: azure/aks-set-context@v3
     with: 
       resource-group: adm-deejayac1
       cluster-name: webappaks
       admin: 'false'
       use-kubelogin: 'true'
        
   - name: Deploy application to AKS
     run: |
       kubectl apply -f /home/adm-deepika/azuredemoproject/Deployment.yaml

   - name: Update kubernetes service 
     run: | 
        kubectl apply -f /home/adm-deepika/azuredemoproject/service.yaml


     
       
       
 
