name: Deploy application to AKS 

on:
 push:
   branches:
   - main

jobs:
 deploy: 
   runs-on: ubuntu-latest

steps:
- name: checkout code
  uses: actions/checkout@v2

- name: Login to Azure CLI 
  uses: azure/login@v1
  with:
    username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
    password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
   
    
